# Generated by Django 6.0.4 on 2026-04-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMiniAppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('language_code', models.CharField(blank=True, max_length=16)),
                ('photo_url', models.URLField(blank=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('allows_write_to_pm', models.BooleanField(default=False)),
                ('last_auth_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Mini App user',
                'verbose_name_plural': 'Telegram Mini App users',
                'ordering': ['-updated_at'],
            },
        ),
    ]
